"""add partial unique index for overall finance budget

Revision ID: cb6c4fdc3ebf
Revises: c7076896a3c4
Create Date: 2026-08-03 08:01:00.767126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb6c4fdc3ebf'
down_revision: Union[str, Sequence[str], None] = 'c7076896a3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_finance_budgets_user_overall', 'finance_budgets', ['user_id'], unique=True, postgresql_where=sa.text('category_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_finance_budgets_user_overall', table_name='finance_budgets', postgresql_where=sa.text('category_id IS NULL'))
    # ### end Alembic commands ###
